version: '3.8'

services:
  frontend:
    image: alicankuklaci/swarmui-master-frontend:latest
    ports:
      - "1519:80"
    networks:
      - swarmui-master-net
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  backend:
    image: alicankuklaci/swarmui-master-backend:latest
    environment:
      NODE_ENV: production
      BACKEND_PORT: 3001
      FRONTEND_URL: http://212.83.131.111:1519
      CORS_ORIGINS: http://212.83.131.111:1519
      MONGODB_URI: mongodb://admin:151575!s@mongo:27017/swarmui-master?authSource=admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: "151575!s"
      JWT_ACCESS_EXPIRES_IN: 15m
      JWT_REFRESH_EXPIRES_IN: 7d
      THROTTLE_TTL: 60000
      THROTTLE_LIMIT: 100
      DOCKER_SOCKET_PATH: /var/run/docker.sock
      JWT_ACCESS_SECRET: "033b54a27045d38499659ed6c8cd963963fab859798a7585ed8a379992b9d4c7"
      JWT_REFRESH_SECRET: "2361f08ac2d7b24f1ba201a7506a727fc461a354711a3ca8c5ea26cd91ad8f7823aac032a69966a4ce684ac8da85360275c0d6376e720a37286ff235eade1011"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - swarmui-master-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: "151575!s"
      MONGO_INITDB_DATABASE: swarmui-master
    volumes:
      - mongo_data:/data/db
    networks:
      - swarmui-master-net
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  redis:
    image: redis:7.2-alpine
    command: redis-server --requirepass "151575!s"
    volumes:
      - redis_data:/data
    networks:
      - swarmui-master-net
    deploy:
      replicas: 1

volumes:
  mongo_data:
  redis_data:

networks:
  swarmui-master-net:
    driver: overlay

