version: '3.8'
services:
  swarmui-agent:
    image: alicankuklaci/swarmui-agent:latest
    ports:
      - "9001:9001"
    environment:
      - AGENT_TOKEN=supersecret
      - AGENT_READONLY=false
      - DOCKER_SOCKET=/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
